spring:
  datasource:
    url: jdbc:mysql://localhost:3306/umc_study_week3
    username: ${MYSQL.USERNAME}
    password: ${MYSQL.PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
